version: "3.4"

# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      TRUSTED_HOSTS: ^${SERVER_NAME:-project-manager\.localhost|localhost}|php$$
      DATABASE_URL: postgresql://user:password@database:5432/db_name?serverVersion=15&charset=${POSTGRES_CHARSET:-utf8}
      POSTGRES_DB: db_name
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_name}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  node:
    env_file: .env
    ports:
      - 5173:5173
    build:
      context: ./docker/node/
      args:
        - HOST_USER=${HOST_USER:-1000}
        - HOST_USERGROUP=${HOST_USERGROUP:-1000}
    restart: unless-stopped
    volumes:
      - ./:/home/docker
    command: "yarn dev"

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - 1025
      - "8025:8025"

volumes:
  db-data:
